apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sammwise-tls-prod
spec:
  secretName: sammwise-tls-prod
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: sammwise-issuer
  commonName: sammwise.vzxy.net
  dnsNames:
  - sammwise.vzxy.net