{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sammwise-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/issuer: "sammwise-issuer"
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"
spec:
  rules:
    - host: {{ .Values.ingress.ingress-domain }}
      http:
        paths:
          - backend:
              service:
                name: sammwise
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - {{ .Values.ingress.ingress-domain }}
      secretName: sammwise-tls-prod
{{- end }}