apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sammwise-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ops@sjultra.com
    privateKeySecretRef:
      name: sammwise-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik