apiVersion: apps/v1
kind: Deployment
metadata:
  name: sammwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sammwise
  template:
    metadata:
      labels:
        app: sammwise
    spec:
      containers:
        - name: sammwise
          image: {{ .Values.sammwise.image }}
          {{- if not .Values.ingress }}
          env:
            - name: NEXT_PUBLIC_BASE_PATH
              # value: {{ .Values.sammwise.NEXT_PUBLIC_BASE_PATH }}
              value: "/k8s/clusters/{{ .Values.global.fleet.cluster.name }}/api/v1/namespaces/sammwise/services/http:sammwise:80/proxy"
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sammwise
spec:
  selector:
    app: sammwise
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000



NEXT_PUBLIC_BASE_PATH