apiVersion: apps/v1
kind: Deployment
metadata:
  name: sammwise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sammwise
  template:
    metadata:
      labels:
        app: sammwise
    spec:
      containers:
        - name: sammwise
          image: {{ .Values.sammwise.image }}
---
apiVersion: v1
kind: Service
metadata:
  name: sammwise
spec:
  selector:
    app: sammwise
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000

